# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# Just for troubleshooting
#init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# version format
version: 0.1.{build}-alpha

branches:
  # whitelist
  only:
  - faceDetection

image: Visual Studio 2015

clone_depth: 10

skip_tags: true

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  
before_build:
  - nuget restore FaceDetection\FaceDetection.sln -SolutionDirectory FaceDetection\
  
#after_build:
#  - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe" FaceDetection\FaceDetection.sln /Build Release /project FaceDetection\FaceDetectionInstaller\FaceDetectionInstaller.vdproj /projectconfig Release'
  
#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: x86

configuration: Debug

build:
  verbosity: normal
  project: FaceDetection/FaceDetection/FaceDetection.csproj
  
artifacts:
  - path: FaceDetection\FaceDetection\bin\$(platform)\$(configuration)
    name: facedetection_portable_x86
    type: zip


test: off
